# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/bl>

# 1. Aturan untuk Layar Utama Laptop Legion (Sesuaikan jika nama monitor utama bukan eDP-1)
monitor = eDP-1, highres, auto, 1.5

# 2. Aturan Otomatis Proyektor (HDMI-A-1) saat dicolok
# Format: nama_port, resolusi, posisi_auto, skala_auto, mirror_ke_layar_laptop
monitor = HDMI-A-1, highrr, auto, 1.5, mirror, eDP-1

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher


bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hy>
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu

# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.

# Scroll to switch workspaces
bind = SUPER, mouse_up, workspace, +1
bind = SUPER, mouse_down, workspace, -1

# Mencegah XWayland blur saat menggunakan scaling
xwayland {
    force_zero_scaling = true
}
