# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/bl>


$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher


bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hy>
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu

# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.

# Scroll to switch workspaces
bind = SUPER, mouse_down, workspace, r+1
bind = SUPER, mouse_up, workspace, r-1
